name: publish_demos_gstlearn

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'
        required: false
        default: ''

env:
  PYTHON_VERSION : "3.11"
  R_VERSION : "4.2.3"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout gstlearn repository
      uses: actions/checkout@v3
      with:
        repository: gstlearn/gstlearn
        token: ${{ secrets.GH_PAT }}
        path: gstlearn

    - name: Install System dependencies
      run: sudo apt install pandoc jupyter libsuitesparse-dev

    - name: Setup Python version
      uses: actions/setup-python@v4
      with:
        python-version: ${{env.PYTHON_VERSION}}
        
    - name: Setup R version
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{env.R_VERSION}}

    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        python -m pip install numpy nbconvert matplotlib pandas scipy jupyter pypandoc scikit-sparse geopandas plotly
        python -m pip install gstlearn
        
    - name: Install R packages
      run: |
        install.packages(c("ggplot2","ggpubr","parallel","FNN","rmarkdown","knitr"))
        install.packages("flumy", repos="https://soft.mines-paristech.fr/cran")
        install.packages("gstlearn", repos="https://soft.mines-paristech.fr/cran")
      shell: Rscript {0}

    - name: Build demonstration HTMLs
      run: |
        mkdir -p demos
        mkdir -p demos/python
        mkdir -p demos/r
        ./gstlearn/doc/build_ipynb_html.sh gstlearn/doc/demo demos/python gstlearn/python/run_test_ipynb.py
        ./gstlearn/doc/build_rmd_html.sh   gstlearn/doc/demo demos/r      gstlearn/r/run_test_rmd.R
        PROJECT_VERSION=$(python -c "import gstlearn as gl; print(gl.__version__)")

    - uses: actions/upload-artifact@v3 
      with:
        # This will become the folder name in the server
        name: demos-${{ env.PROJECT_VERSION }}
        path: demos

  publish:
    needs: build
    # Only ubuntu can upload easily (ssh)
    runs-on: ubuntu-latest
    
    steps:
    - uses: fabien-ors/folder-publish-action@v1
      with:
        host: ${{ secrets.CG_HOST }}
        username: ${{ secrets.CG_USR }}
        password: ${{ secrets.CG_PWD }}
        dest-path: "/var/www/html/gstlearn"
        
    # Delete the artifacts (for freeing storage space under github)
    - uses: geekyeggo/delete-artifact@v2
      with:
        name: demos-*
